save unit test results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,7 +16,16 @@ jobs:
           pip install build setuptools wheel twine
           pip install -e .[dev]
       - name: Run UnitTest
-        run: python -m unittest discover -s test -p "test_*.py" -v
+        run: |
+          set +e
+          python -m unittest discover -s test -p "test_*.py" -v > result.log 2>&1
+          exit_code=$?
+          if [ $exit_code -eq 0 ]; then
+            echo "TEST_RESULT=✅ Tests passed" >> $GITHUB_ENV
+          else
+            echo "TEST_RESULT=❌ Tests failed" >> $GITHUB_ENV
+          fi
+          cat result.log
       - name: Update README with test result
         uses: actions/github-script@v7
         with:
